### PR TITLE
Timestamp ranges not matched the same way org-agenda does

### PR DESCRIPTION
**Pull request by yantar92**
I have a headline like the following:

    ***** NEXT [#A] Manuel Macías [Email] (2021) "Continuous Integration and TeX with Org-Mode", by Rohit Goswani (TUG 2021) :BOOKMARK:misc:email:
    SCHEDULED: <2021-08-07 Sat 16:30-17:30>

I expect this headline to be matched by `(scheduled 0)` sexp, but it is not.

### CODE REVIEW

**Comment by alphapapa** [comment]
Retargeting this for 0.7.  0.6 has been delayed for too long.

**Comment by stfl** [comment]
It's also relevant for `ts-active` timestamps. In particular this shows up for me when syncing my calendar with org-gcal which will create active ranged timestamps.

**Comment by enko** [comment]
Anything hindering this pr to be merged?

**Comment by alphapapa** [comment]
@enko Well, yes: since this has been a bug, the fix should be accompanied by explicit tests, i.e. there should be a new test added for timestamp ranges, rather than just changing one of the test data entries, as the PR currently does.  Maybe even multiple tests for active/inactive timestamps, in planning/deadline/scheduled lines, and in headings/content.

It also needs a changelog entry--which I typically take care of myself when merging, but if a contributor provides it in the patch, it saves me the time and makes it easier for me to merge (assuming it's done correctly; even when I ask someone to provide one, and they do, it usually contains typographical errors that I have to fix myself, which defeats the purpose).

Other than that, the limitation is time, which I don't have as much of as I used to.

In the meantime, you're free to use the PR's code and report back as to how well it works.  Any bugs you could discover before merging would be helpful.

**Comment by alphapapa** [comment]
As well, fixing this properly probably requires more work, because a ranged timestamp essentially represents two timestamps, one at each end of the range, and searching for timestamps within specific ranges must account for both of them.

**Comment by dmitrym0** [comment]
Do you think it's possible to split this is up into two tasks:

1. getting ranged timestamp to match `scheduled` and `planning` 
2. searching for a timestamp in a range.

I came here look for 1, looks like I'm not the only one. Would be happy to contribute tests for it as well and improve the original request.

**Comment by magogware** [comment]
I tried out your most recent commit @dmitrym0 and had no luck with either the scheduled predicate or the ts-active predicate.

**Comment by dmitrym0** [comment]
@magogware 

Here's a part of my test data:

```
* TODO This heading should be there because it contains scheduling info with time
SCHEDULED: <2026-01-23 Sun 14:00-15:00>
:PROPERTIES:
:ID:       FAKE_ID1
:END:
```

and the associated org-ql query that returns it:

```
'(or
  (ts-active)
  (clocked)
  (and
   (todo "TODO" "DONE")
   (or
    (scheduled) (planning))))
```

**Comment by magogware** [comment]
Ack, sorry. A (Doom) Emacs restart ensured I was actually using the package built from your commit, and now everything works. Cheers! It all works a charm.

**Comment by dmitrym0** [comment]
Can't take credit for it; so thanks to @yantar92. Of course caveat emptor since this hasn't been properly tested.

**Comment by alphapapa** [comment]
FYI, it appears that something in the Buttercup library has changed, and now the test suite goes into an infinite loop and never terminates.  Obviously, this presents a bit of a roadblock to developing this and other fixes and features.  And my time and enthusiasm for debugging a third-party library that used to work fine is limited.  

I've half a mind to convert all the tests to use ERT, but I like Buttercup's nice-looking, grouped and colorized output.  Maybe what's needed is some kind of lightweight wrapper around ERT to use ERT as a backend while providing nicer output and test grouping.

Anyway, if anyone would like to dig into Buttercup's recent changes and figure out why it's broken, that would certainly be appreciated.  Otherwise, it seems that I will have to find time to do some serious yak shaving (or skinning, even).

**Comment by ivanperez-keera** [comment]
I'm not a lisp programmer so I can't really help by adding tests, but as a frequent user of ranges in timestamps, I'll be happy to test a version when it's ready to be merged or it's just released.

**Comment by alphapapa** [comment]
Visiting this issue again, testing confirms that fixing this issue will require more than just adjusting the regexp in `org-ql-regexp-part-ts-time`, because timestamps with time ranges like this must be handled correctly by other code.

So, given the number of new features in v0.7, I'm retargeting this for v0.8 so as not to further delay the release of v0.7.

**Comment by ivanperez-keera** [comment]
I'd be keen to see this merged. Let me know if I can help; maybe I can try a branch before it's ready to merge. I use ranges extensively in my org files, so I have plenty of examples.

**Comment by alphapapa** [comment]
> I'd be keen to see this merged. Let me know if I can help; maybe I can try a branch before it's ready to merge. I use ranges extensively in my org files, so I have plenty of examples.

I understand.  I regret the delay, but as I said, fixing it without introducing other bugs will require more work.  If there's some subset of the changes that works for you, feel free to use them, but I can't recommend using partially implemented changes.

**Comment by ParetoOptimalDev** [comment]
I'm getting more friction from this issue lately as I now use 

So... I'm interested in contributing here but I'm unclear on exactly the target is for it being done and being reasonably sure there are no regressions.

I see:

>  the fix should be accompanied by explicit tests, i.e. there should be a new test added for timestamp ranges, rather than just changing one of the test data entries, as the PR currently does. Maybe even multiple tests for active/inactive timestamps, in planning/deadline/scheduled lines, and in headings/content.

> It also needs a changelog entry

> testing confirms that fixing this issue will require more than just adjusting the regexp in org-ql-regexp-part-ts-time, because timestamps with time ranges like this must be handled correctly by other code.

> Anyway, if anyone would like to dig into Buttercup's recent changes and figure out why it's broken, that would certainly be appreciated. 

So from that the checklist in my mind would be:

```org
* explicit tests
** add new test(s) for timestamp ranges
** 3-5 or more tests for active/inactive timestamps for across in planning
** 3-5 or more tests for active/inactive timestamps for across in scheduled
** 3-5 or more tests for active/inactive timestamps for across in deadlines
** 3-5 or more tests for active/inactive timestamps for across in headings
** 3-5 or more tests for active/inactive timestamps for across in content
* handle time rangers correctly in other code
** determine other code that needs to handle timestamps
* fix buttercup tests looping
** verify that buttercup tests still loop
```

I think if we could figure out a checklist that is likely to get merged or not get stuck because of a lack of confidence we can make progress on this. My biggest question and perhaps also the biggest unanswered question for you is where the other code is that needs to handle timestamps for a change like this.

Perhaps just adding the tests above or perhaps the above and any additions you may add will answer the question of what those places are?

**Comment by ivanperez-keera** [comment]
Echoing @ParetoOptimalDev , what are the exact things that would need to be done for this to be complete?

It's 100% understandable if you cannot make this a priority, @alphapapa . This project is big and we are lucky that it works already as well as it does :smiley: 

If you are able to enumerate the actions required, maybe others can complete them.

**Comment by alphapapa** [comment]
@ivanperez-keera I'll try to summarize what comes to mind:

1. First, since we're aiming to upstream at least part of `org-ql` into Org-mode, any contributions with regard to this issue would have to be made by someone who's done the FSF copyright assignment for Emacs.
2. Given that, as I mentioned in [https://github.com/alphapapa/org-ql/pull/237#issuecomment-1463725161](this comment), what's needed is to ensure that all the code that works with timestamps also works with timestamp ranges.  

   That's probably not a trivial change, because it likely means passing one or two timestamps (e.g. a cons of beginning and end timestamps) everywhere (or almost everywhere) one timestamp is currently handled.  Probably some wrapper macro and/or function would be written to help facilitate that where appropriate.  

   Alternatively, maybe Org element objects which are Org timestamp ranges could be passed around.  But that would probably mean 1) parsing them into `ts` objects in more places, which might reduce performance; and 2) changing code in a lot of places, including possibly turning `ts` objects into Org element timestamp objects sometimes.
3.  Finally, tests need to be added that test functionality with Org files containing timestamp ranges in various places (active/inactive, "standalone" ones, ones in planning (scheduled/deadline/closed) lines, logbook drawers, etc.

Looking back, I suppose this was a somewhat significant oversight on my part, to not realize that timestamps can have time ranges (something I never use in my own Org files).  Thankfully it seems that not many other users use them, or else Org QL would probably be much less useful than it is.

Anyway, that's what comes to mind.  Actually digging in to the code might reveal more or fewer problems to deal with.

If someone who has done the FSF CA wants to work on this, I'll be glad to provide feedback (but with the caveat that I aim for very high quality code on this project, and I'm very particular (realizing of course that there are probably people out there who think my code is atrocious, haha)).

**Comment by ivanperez-keera** [comment]
org-ql together with timestamp ranges enables some pretty advanced forms of planning. I manage everything I do with org-mode, both at work and in my personal life, and scheduling tasks with ranges allowed me to plan full weeks of tasks with minute precision -- and stick to the plan.

I hope someone who knows lisp can help by sending a PR that meets Adam's requirements. I can contribute by trying this on large files.

Not sure if that will help, but I'll happily buy whoever works on this a few rounds of coffee, or a drink of your choice -- whatever keeps you going while you code :)

**Comment by alphapapa** [comment]
> org-ql together with timestamp ranges enables some pretty advanced forms of planning. I manage everything I do with org-mode, both at work and in my personal life, and scheduling tasks with ranges allowed me to plan full weeks of tasks with minute precision -- and stick to the plan.

I'd like to read more about that, because it would be helpful to me too.

> Not sure if that will help, but I'll happily buy whoever works on this a few rounds of coffee, or a drink of your choice -- whatever keeps you going while you code :)

FWIW, I do intend to see that this is solved, whether the code is written by me or someone else.  It's just a case of limited time and professional priorities right now, for myself to do it.  If someone were interested, I'd be open to the idea of the work on this project feature being sponsored, either by an individual or through a bounty program; that would allow me to prioritize doing the work myself.

**Comment by ivanperez-keera** [comment]
> I'd like to read more about that, because it would be helpful to me too.

I've been meaning to write about this, but --not a joke-- lately finding time has become hard because of this missing feature :sweat_smile: 

> It's just a case of limited time and professional priorities right now, for myself to do it.

That's absolutely understandable. I'm on the same boat with the projects I maintain.

> If someone were interested, I'd be open to the idea of the work on this project feature being sponsored, either by an individual or through a bounty program; that would allow me to prioritize doing the work myself.

I'd be open to this.

I don't know how big a bounty we are talking; I doubt I'd be able to contribute a big enough amount to change your priorities, but if several of us are willing to chip in, then maybe we'll get there.

Also, it may make sense to let others who submit a PR take the bounty even if we don't get to an amount that would allow you to do it. They may have a bit more time and be willing to do it even if you can't.

**Comment by alphapapa** [comment]
> I've been meaning to write about this, but --not a joke or some messed up passive aggression-- lately finding time has become hard because of this missing feature 😅

LOL  :)

Regarding a bounty: I'd probably only be willing to be involved in something like that if it were explicitly intended, from the beginning, to sponsor my working on the feature, not anyone else.  The reason is not to deny anyone else the opportunity to work on it and benefit from a bounty.  The reason is that, if someone else did the work and wanted to claim the bounty, I would still be involved, as it would be my responsibility to evaluate the code and decide whether to merge it; and if I rejected it, or if I required changes that the other developer did not want to make, I would not want to deal with conflict over whether the bounty should be claimed, whether it should be divided among various participants, whether my requirements were reasonable, etc.

So I think it would be better considered as an opportunity to sponsor the author to implement a specific feature with priority over other features.

Of course, I can't control what anyone else does; if someone were to start a bounty somewhere, and that resulted in code being submitted (with proper copyright assignment), I wouldn't necessarily reject it.  But I would not give any consideration to the bounty being involved.  My objective is to have high-quality code.

I hope you understand what I mean.  When money gets involved, everything changes, and one has to be very careful.  It's best to be as clear as possible from the beginning.

**Comment by dmitrym0** [comment]
I rely on scheduled time ranges heavily, though org manual seems to discourage this.

I wrote a small package to plan my days: [org-hyperscheduler](https://github.com/dmitrym0/org-hyperscheduler). I use org-ql to surface tasks and task-like things though `SCHEDULED` entries with a range require a patched version of org-ql.

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

>> I rely on scheduled time ranges heavily, though org manual seems to discourage this.
>
> Does it?

We recommend using active timestamps for appointments. Not SCHEDULE.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by alphapapa** [comment]
> > > I rely on scheduled time ranges heavily, though org manual seems to discourage this. 

>> Does it?

> We recommend using active timestamps for appointments. Not SCHEDULE.

Right; I was referring to the use of ranges in the timestamp.

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

>> > > I rely on scheduled time ranges heavily, though org manual seems to discourage this. 
>
>>> Does it?
>
>> We recommend using active timestamps for appointments. Not SCHEDULE.
>
> Right; I was referring to the use of ranges in the timestamp.

SCHEDULE in Org mode is supposed to be the time when to start working on
the task. Time range there does not make a lot of sense. It only makes
sense when the task is actually an appointment spanning certain hours in
a day.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by ivanperez-keera** [comment]
> SCHEDULE in Org mode is supposed to be the time when to start working on
> the task. Time range there does not make a lot of sense. It only makes
> sense when the task is actually an appointment spanning certain hours in
> a day.

Could this recommendation in org-mode be changed? The SCHEDULE value would then be interpreted as the start time and/or block when the task will be performed.

Using ranges with scheduled tasks is very convenient to plan: assigning task finish times is convenient (much more IMO than using the duration support in org-mode), and the agenda makes it easy to see that you are not planning things for overlapping times.

**Comment by dmitrym0** [comment]
> Does it?

Indeed: 

> Important: Scheduling an item in Org mode should not be understood in the same way that we understand scheduling a meeting. Setting a date for a meeting is just a simple appointment, you should mark this entry with a simple plain timestamp, to get this item shown on the date where it applies. This is a frequent misunderstanding by Org users. In Org mode, scheduling means setting a date when you want to start working on an action item.

[source](https://orgmode.org/manual/Deadlines-and-Scheduling.html)

I agree with @ivanperez-keera.

When I "schedule an item", I am scheduling it like an appointment. It has a start and an end. The purpose is to prevent overcommitments and optimize around actual meetings and appointments.

**Comment by alphapapa** [comment]
@dmitrym0 I was talking specifically about the use of ranges in timestamps.  The matter of what Org intends a "SCHEDULED" timestamp to mean is a perennial question, misunderstood by nearly every new user.  In hindsight, the choice of term may have been a mistake, but it probably made sense to Carsten when he added the feature.  :)  In fairness, it's hard to find a word that means something like, "This is a task that I intend to work on not before this date," or perhaps more specifically, "This is a task that I want to appear on my agenda starting on this date and remaining until it is completed or rescheduled."

**Comment by ivanperez-keera** [comment]
> SCHEDULED commands are convenient for setting and updating such a timestamp

It's even more than that. Query languages (including org-mode's own for building sparse trees and such) have specific keywords for querying the SCHEDULED timestamp.

> There's nothing necessarily wrong with using them that way; but one should be aware of the assumptions that Org makes about them.

Give that it's a widespread use (or abuse), I think it would make sense to consider changing org-mode to not make such assumptions.

**Comment by yantar92** [comment]
"Ivan Perez, PhD" ***@***.***> writes:

>> There's nothing necessarily wrong with using them that way; but one should be aware of the assumptions that Org makes about them.
>
> Give that it's a widespread use (or abuse), I think it would make sense to consider changing org-mode to not make such assumptions.

Then, the workflow for people who are using SCHEDULED as time to start
working on a task will be broken. So, it is a no-go.

There might be some kind of custom option, but I do not have a clear
picture of the workflow you are proposing. If you have a detailed
proposal on the alternative use of scheduled keyword, feel free to post
it on the mailing list.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by alphapapa** [comment]
My best idea would be to add support for "generic planning timestamps," which would mean something like having an option defining a list of planning keywords, to include the defaults of DEADLINE, SCHEDULED, and CLOSED, which could appear in the planning line of an entry.  Then a user who wanted to distinguish between the two meanings could add a new one, e.g. STARTING.

I have no idea how much work such a change would entail.   I'd guess it would require a general refactoring of everywhere that uses planning lines and timestamps, and probably changes to `org-element` too, so it would probably be non-trivial.

**Comment by alphapapa** [comment]
Short of that, a user like Ivan could probably write some custom code to use a custom property, e.g. WORKING, whose value could be a timestamp. Then a custom search predicate could be defined using org-ql-defpred which would allow it to be queried like other planning timestamps. That wouldn't require any changes to Org itself.

**Comment by ivanperez-keera** [comment]
> Then, the workflow for people who are using SCHEDULED as time to start working on a task will be broken. So, it is a no-go.

@yantar92  Not really. I'm not suggesting that we make SCHEDULE a mandatory range. Just that we allow a range. If there's only one time, then that's the start time. If there's a range, then that's a start time and an end time.

I don't understand how that _breaks_ anybody's workflow. It only adds. It does not subtract.

I regularly use it with both meanings. I did for 15 years. I only found out that I'm not supposed to use it that way as a result of this conversation (this very pull request).

**Comment by ivanperez-keera** [comment]
> planning line of an entry.

What's the planning line of an entry?

> Short of that, a user like Ivan could probably write some custom code to use a custom property, e.g. WORKING, whose value could be a timestamp. Then a custom search predicate could be defined using org-ql-defpred which would allow it to be queried like other planning timestamps.

This sounds like it could work for org-ql specifically, but a lot of things would stop working in org-mode for those who switch properties. That definitely will break their (our) workflow.

**Comment by yantar92** [comment]
"Ivan Perez, PhD" ***@***.***> writes:

> @yantar92 Not really. I'm not suggesting that we make SCHEDULE a
> mandatory range. Just that we allow a range. If there's only one time,
> then that's the start time. If there's a range, then that's a start
> time and an end time.
>
> I don't understand how that _breaks_ anybody's workflow. It only adds. It does not subtract.

I am not 100% sure if I understand your workflow. I am just guessing that
you want something like

* TODO This is test with time range
SCHEDULED: <2024-04-20 Sat 22:00-23:00>

to be displayed as

Saturday   20 April 2024
* today      inbox: 22:00-23:00 TODO This is test with time range
Monday     22 April 2024 W17
*  1 d. ago  inbox: 22:00-23:00 TODO This is test with time range

However, it is now displayed as

Saturday   20 April 2024
* today      inbox: 22:00-23:00 TODO This is test with time range
Sunday     21 April 2024
*  1 d. ago  inbox: TODO This is test with time range

> I regularly use it with both meanings. I've been doing so for about 15
> years. I only found out that I'm not supposed to use it that way as a
> result of this conversation (this very pull request).

Nothing stops you from using it. It is just that some things like the
above agenda display may be slightly surprising.

A more problematic workflow is using SCHEDULED for one-off events, like
scheduled meetings - if not marked DONE, such meeting will keep
appearing in agenda for the next days.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by ivanperez-keera** [comment]
>  I am just guessing that you want something like
> 
> * TODO This is test with time range
> SCHEDULED: <2024-04-20 Sat 22:00-23:00>
> 
> to be displayed as
> 
> Saturday   20 April 2024
> * today      inbox: 22:00-23:00 TODO This is test with time range
> Monday     22 April 2024 W17
> *  1 d. ago  inbox: 22:00-23:00 TODO This is test with time range

No.

> It is now displayed as
> 
> Saturday   20 April 2024
> * today      inbox: 22:00-23:00 TODO This is test with time range
> Sunday     21 April 2024
> *  1 d. ago  inbox: TODO This is test with time range

That's fine. It's consistent with using the SCHEDULED time as a start time, which shows as the latter:

Saturday   20 April 2024
* today      inbox: 22:00 TODO This is test with stat time only
Sunday     21 April 2024
*  1 d. ago  inbox: TODO This is test with stat time only

> the above agenda display may be slightly surprising.

I never found that surprising because it's consistent with how the agenda shows for past items with only a start time.

> A more problematic workflow is using SCHEDULED for one-off events, like scheduled meetings - if not marked DONE, such meeting will keep appearing in agenda for the next days.

What do you mean? Why wouldn't they be marked as done? I'm not following this last bit.

**Comment by ivanperez-keera** [comment]
By the way, I have no idea if it makes a difference by I normally do: `<2024-04-20 Sat 22:00>--<2024-04-20 Sat 23:00>`

**Comment by yantar92** [comment]
"Ivan Perez, PhD" ***@***.***> writes:

> Saturday   20 April 2024
> * today      inbox: 22:00 TODO This is test with stat time only
> Sunday     21 April 2024
> *  1 d. ago  inbox: TODO This is test with stat time only
>
>> the above agenda display may be slightly surprising.
>
> I never found that surprising because it's consistent with how the
> agenda shows for past items with only a start time.

Then, your use case perfectly fits "In Org mode, scheduling means
setting a date when you want to start working on an action item."
There is no problem. Your use case is then perfectly covered.

>> A more problematic workflow is using SCHEDULED for one-off events,
>> like scheduled meetings - if not marked DONE, such meeting will keep
>> appearing in agenda for the next days.
>
> What do you mean? Why wouldn't they be marked as done? I'm not following this last bit.

* Meeting on Saturay
SCHEDULED: <2024-04-20 Sat 14:00-16:00>

will keep being displayed again and again in agenda:

Saturday   20 April 2024
* today      inbox:         [    ] 14:00-16:00     +0.4x     Meeting on Saturay
Sunday     21 April 2024
*  1 d. ago  inbox:         [    ]     +0.4x     Meeting on Saturay

until you do

* DONE Meeting on Saturay
SCHEDULED: <2024-04-20 Sat 14:00-16:00>

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by ivanperez-keera** [comment]
I'm so confused. For me, it shows up exactly the same way regardless of whether a range is used or not. I don't understand what's wrong, @yantar92 , or what you would expect.

# With ranges

Assuming the task was not completed on time, it shows up as undone today (one day late), and does not show up in future agendas (yet).

image
image

# Without ranges

Assuming the task was not completed on time, it shows up as undone today (one day late), and does not show up in future agendas (yet).

image
image

I still think this conversation is relevant to this issue, since its related to the use of ranges, but I'm ok taking this offline if @yantar92 prefers. I don't know if the mailing list is the right place.

**Comment by ivanperez-keera** [comment]
I'm so confused. For me, it shows up exactly the same way regardless of whether a range is used or not. I don't understand what's wrong, @yantar92 , or what you would expect.

# With ranges

Assuming the task was not completed on time, it shows up as undone today (one day late), and does not show up in future agendas (yet).

image
image

# Without ranges

Assuming the task was not completed on time, it shows up as undone today (one day late), and does not show up in future agendas (yet).

image
image

I still think this conversation is relevant to this issue, since its related to the use of ranges, but I'm ok taking this offline if @yantar92 prefers. I don't know if the mailing list is the right place.

**Comment by alphapapa** [comment]
> I still think this conversation is relevant to this issue, since its related to the use of ranges, but I'm ok taking this offline if @yantar92 prefers. I don't know if the mailing list is the right place.

This sub-thread seems to be about the semantics of SCHEDULED timestamps as interpreted by users and as implemented by Org Agenda.  But this issue is supposed to be about Org QL's support for timestamps with internal time ranges.  So, yes, please continue it on the mailing list, or on a thread on this repo's Discussions forum.  If you do, feel free to post a comment here with a link.

In the meantime, I'm going to mark the relevant comments here as off-topic so the issue can remain focused on the technical issues regarding Org QL.  No hard feelings; conversations work this way.  :)

**Comment by ivanperez-keera** [comment]
I've now added this change to my installation of org-ql (merging it individually as I have org-ql installed with elpa).

I know this is not representative of all tests that should be performed, but this seems to be working well for me so far. I'll report back if I notice any issues.

I have a file with more than 15 years worth of history. It won't be representative of all possible cases, but it's also not a trivial test.

**Comment by alphapapa** [comment]
> I've now added this change to my installation of org-ql (merging it individually as I have org-ql installed with elpa).
> 
> I have a file with more than 15 years worth of history. It won't be representative of all possible cases, but it's also not a trivial test.
> 
> It seems to be working well for me so far. I'll report back if I notice any issues.

Thank you, I would appreciate that.  My time for these projects has been limited lately, and ones that require careful review and testing like this are the hardest to find time for.

**Comment by ParetoOptimalDev** [comment]
> I've now added this change to my installation of org-ql (merging it individually as I have org-ql installed with elpa).
> 
> I have a file with more than 15 years worth of history. It won't be representative of all possible cases, but it's also not a trivial test.
> 
> It seems to be working well for me so far. I'll report back if I notice any issues.

@ivanperez-keera If you can push your changes up, I can also test with 10+ years of history.

**Comment by ivanperez-keera** [comment]
I'm not sure how to do that, but it's only two lines that need to be adjusted. See: https://github.com/alphapapa/org-ql/pull/237/files#diff-34013f28e9b645ff9d9a6dab1c4f0ca707ae51e0361da84126e8440810452773R162-R163

It's quite easy to just add the change manually.

**Comment by ParetoOptimalDev** [comment]
> It's only two lines that need to be adjusted. See: https://github.com/alphapapa/org-ql/pull/237/files#diff-34013f28e9b645ff9d9a6dab1c4f0ca707ae51e0361da84126e8440810452773R162-R163

This does match `(todo)` which wasn't before, but it doesn't seem to work with `(scheduled :to today)` or `(ts-active :on today)`.

For example with that change this data:

```
*** TODO 15 minutes, standup
   SCHEDULED: <2024-06-24 Mon 09:00-09:15 ++7d>
```

Doesn't match `(or (scheduled :to today) (ts-active :on today))`.

**Comment by alphapapa** [comment]
@ParetoOptimalDev It works for me.  It's likely that you did not load the changed library file correctly.  i.e. `defvar` forms do not change the values of already-defined variables unless you individually set them with `C-M-x`, and doing that to one does not do that to others that depend on its value.

**Comment by alphapapa** [comment]
v0.8.7 will allow such ranges to be matched simply, but matching depending on the specific inner time ranges will not work yet.  That will require some refactoring, and so it will be done in a future version (maybe v0.9, maybe not).

**Pull request merged**
