### PR TITLE
Add org-agenda-text-search-extra-files to options to search

### PR DESCRIPTION
**Pull request by egh**
`org-agenda-text-search-extra-files` is a useful thing to be able to search.

### CODE REVIEW

**Comment by alphapapa** [comment]
Unfortunately, this patch will not produce the desired effect.  Please see the subsequent lines in the function to see how the code works.

This may be a useful feature to have, but this may not be the best way to implement it.  It might be better to make it a `defcustom` that enables the additional files to be searched when `org-agenda-files` are searched.

**Comment by egh** [comment]
Thanks for the feedback! It seems to be working fine for me when I run `org-ql-search` - am I missing something? Thanks.

image

Results after search:

image

```
org-agenda-text-search-extra-files is a variable defined in org.el.

Value
("/home/egh/c/notes/h/research/people.org")
```

**Comment by alphapapa** [comment]
I see what's going on now: this patch does work as intended, but it works because of a bug in this `pcase` clause:

```el
((and form (guard (rx bos "("))) (-flatten (eval (read form))))
```

The `(guard (rx bos "("))` does not work as I intended: I thought that the `rx` form would be evaluated as a `pcase` `rx` clause, which would test it against the value being matched against, but instead it's macro-expanded to a string, which the `guard` accepts as a non-nil value.  So the string, which is the variable's name, is passed to `(eval (read form))`, and the value of that variable is returned.

As well, the function `org-ql-view--contract-buffers-files` would need to be updated to handle this new choice.

However, as I said, I'm reluctant to add support for this variable as a choice in the completion, because 1) its name is very long, and 2) AFAICT very few Org users know that it exists.  I think this is only the second time I've ever seen it mentioned by anyone in all the years I've used Org.

So I'd prefer to support it in another way.  Here are a couple of ideas:

1.  As I suggested, a new customization option that would apply to when `org-agenda-files` is selected as the set of files.  Implementing this might be a little messy, though, as it would require more checks and probably another `defvar` as well.
2.  A way for users to add additional choices to the completion choices.  This might be more work, but it would be more flexible, and it would allow users to easily define presets for sets of files to search.  It should probably allow users to specify a Lisp form or a lambda to be evaluated when the choice is selected.

What do you think?  Thanks.

**Comment by egh** [comment]
Thank you for explaining this! I am not very familiar with `pcase` and I just learned about `rx`. The use of the two together makes for elegant elisp code.

I agree, it's an obscure variable. I've found a number of bugs around it. It's unfortunate, because it's nice to have a place for files in org mode that are for pure reference, not for use as agenda items. It can speed up agenda generation.

I will look into how to implement (2). Thank you again for your helpful reply.

**Comment by alphapapa** [comment]
> Thank you for explaining this! I am not very familiar with `pcase` and I just learned about `rx`. The use of the two together makes for elegant elisp code.

Indeed, it's a great example of Lisp's power.  (Of course, at the same time, learning `pcase` can be difficult, because it's so powerful.)

> I agree, it's an obscure variable. I've found a number of bugs around it. It's unfortunate, because it's nice to have a place for files in org mode that are for pure reference, not for use as agenda items. It can speed up agenda generation.

Right.  This is an example of one of the Org Agenda features that I think I don't want to support as-is in `org-ql`, one of the sort-of "crufty" features that we don't really need, because there are better, cleaner ways to do the same thing.

> I will look into how to implement (2). Thank you again for your helpful reply.

Sounds good.  You might want to talk about the design before coding it, because it may need some back-and-forth to arrive at the best solution.

If you don't mind, please open a new issue when you have something ready to share.  Thanks for your help with this.

**Pull request closed without merging**
