### PR TITLE
Changes in org-dblock-write:org-ql

### PR DESCRIPTION
**Pull request by balaramadurai**
Now org-agenda-files can be included as well as any other list of files that work for org-ql.

Useful if you are doing your weekly, quarterly or yearly reviews.

#151 is something that triggered my thoughts.

### CODE REVIEW

**Comment by timinou** [comment]
Hey!

I made a similar change in my config file, and I found that the links generated don't work, because they do not include the full path. That's a limitation of the original code...

You can check that yourself by making a dynamic block that gathers headlines from other files and following the generated links.

I'm pretty new with ELisp so I wasn't able to fix it. Best!

**Comment by balaramadurai** [comment]
@timinou,
  Thank you for your input. Well, I barely know enough elisp myself, but I hacked something from various sources and this seems to work now.

I haven't done extensive tests, but seems to serve my purpose.

Thanks @alphapapa and others for developing such a lovely package!
Bala

**Comment by timinou** [comment]
Thanks @balaramadurai !

I imported your code to my config.org and I had to make two changes:
1. I added a "*" before the heading description (that's how I would see links generated with org-store-link be)
2. I couldn't access headings in files that were not in the same directory as the file that had the dynamic block. In my case, the dynamic block is in journal/2021-01.org, and the headings in question are in actions.org.

I fixed (2) by changing your "format" string to include org-directory, but I don't know if that's the most idiomatic way of doing it, so I didn't push it. Let's see if @alphapapa has a better solution at hand!

Thank indeed to everyone involved for such a useful package! It opens up org-mode's customisation to yet another level.

**Comment by balaramadurai** [comment]
Thanks @timinou for the feedback.

I made changes to two files - `org-ql.el` and `org-ql-search.el` and fixed the file name and * issue for the heading name.

Please let me know if this works for you. It seems to be working for me.

I tested my setup with my org-agenda-files and in a scratch buffer. Seems to be working.

Thanks and have a good day!
Bala

**Comment by alphapapa** [comment]
Thanks for your patience.

I think this PR isn't suitable for merging, because it seems to contain some changes unrelated to the matter at hand (controlling the scope of the block's search).

As well, this enhancement will have to be carefully considered to avoid security risks.  e.g. what kind of argument does the `:file` argument accept?  If it accepts arbitrary Lisp, that would probably be a code-execution vulnerability, allowing anyone who can modify the file to cause arbitrary code to be run next time the block is updated.  I've tried to account for those issues in the other block arguments with extensive tests and argument checking, and that would have to be done for this feature as well.

Since this PR doesn't address those issues, I'm closing it.  Thanks for sending it, though.  Please feel free to continue the discussion on #151.

**Pull request closed without merging**
