### PR TITLE
Store bookmarks & links with multiple files or buffers

### PR DESCRIPTION
**Pull request by tpeacock19**
This is an attempt to address the latest issues I've brought up #147 & #148.

----

#

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks for this.  I think it's probably best if the linking and bookmarking functions work differently.  Theoretically there could be a security concern with links and arbitrary code execution.  I mean, it's extremely unlikely that someone would write an `org-ql-search:` link that does something evil, and then publish that Org file somewhere, and then entice someone to click the link.  But I think we shouldn't discount that possibility entirely.  For example: `[[org-ql-search:(message "AHA!")]]`.  If that were an evil function instead of `message`...

So, in general, I think it's okay for bookmarks to be considered safe (they can already have arbitrary Lisp code in the handler function, AFAIK, and if an attacker could modify a user's bookmarks file, he'd already have full access to the system).  But links can be expected to live in documents which might be published and downloaded.  So while a bookmark could, e.g. call `(org-agenda-files)` to get the list of current files, or call an arbitrary function to return a list of files, I think that links should only use expressions that will be `read` but never `eval`'d.

So, having said all that (which may be more than you are concerned with), I think we should handle these cases differently.  I'm going to work on this issue tonight, so let's take another look at this after I push some more changes.  Thanks.

**Comment by alphapapa** [comment]
Please see https://github.com/alphapapa/org-ql/commit/b217458d04806c943ac5554d8d7522c71bc328dd

**Comment by tpeacock19** [comment]
> So, having said all that (which may be more than you are concerned with), I think we should handle these cases differently. I'm going to work on this issue tonight, so let's take another look at this after I push some more changes. Thanks.

No thank you for going through your process. I knew there had to be a reason as to why you hadn't done it yet and its good to hear your perspective. I did not think about executing lisp functions so props to you.

I think the warning approach is good.

**Comment by alphapapa** [comment]
Thanks.  So with regard to this PR, I'm not sure where we go from here.  Is this still relevant?

**Comment by tpeacock19** [comment]
No i'll close it. More just a personal exercise anyway i guess.

**Pull request closed without merging**
