### PR TITLE
Remove mentions of org-ql-find-heading, org-ql-find-path from Changelog.

### PR DESCRIPTION
**Pull request by ivanperez-keera**
These commands were removed in 5768c685adc7c6e85c17cfec358aa8a0e368310b, but they were still mentioned in the release that was going to incorporate those two functions, v0.7.

### CODE REVIEW

**Comment by alphapapa** [comment]
Isn't `org-ql-find-path` extant?

**Comment by ivanperez-keera** [comment]
I'm not sure what you mean.

According to 5768c685adc7c6e85c17cfec358aa8a0e368310b, `org-ql-find-path` was removed prior to the 0.7 release, and re-introduced in the 0.8 release (in commit ac2d43588aa96f0b7fe88f518d6fca4fd65b5aa0 specifically, which was only merged with the main branch in ace5e361af0e691310dda8ed776a39df3f3898e9.

As it pertains to the changelog, it should be removed from the 0.7 release subheading IMO.

As you prefer.

**Comment by ivanperez-keera** [comment]
I've adjusted the commit message to make things a bit clearer. See if that helps and let me know if not.

**Comment by alphapapa** [comment]
Ah, my mistake.  Thanks.

**Pull request merged**
