### PR TITLE
Fixed line width calculation for helm source

### PR DESCRIPTION
**Pull request by ryan-c-scott**
.Was resulting in negative values on long entries and the resulting
error was being suppressed by `ignore-errors' in the source

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks for working on this.

Looking at the change, I'm not sure if I understand exactly what's happening, or whether this would be the best way to fix it.  If the width variable is set to 0 for certain entries, it might result in a string that isn't useful or readable.  Can you show me an example of an entry that causes this problem, and what the result is after the fix is applied?

**Comment by ryan-c-scott** [comment]
> Thanks for working on this.
> 
> Looking at the change, I'm not sure if I understand exactly what's happening, or whether this would be the best way to fix it. If the width variable is set to 0 for certain entries, it might result in a string that isn't useful or readable. Can you show me an example of an entry that causes this problem, and what the result is after the fix is applied?

I'll try to get a more concrete example for you soon, but the current behavior causes any source that would show one of these long entries to show absolutely nothing at all.

The behavior when that value gets calculated as 0 is just that it effectively uses the whole original string.

Regardless long strings causing that value to be -1 and then throw an invisible error will need to be addressed for usability.

**Comment by ryan-c-scott** [comment]
I also didn't mean to bring in these other changes. Not sure what happened there. I'll get that resolved.

**Comment by alphapapa** [comment]
Ok, thanks.

If you would, since this is a bug fix, please rebase the patch onto the `stable/0.6` branch so I can make a new stable release with this fix.  If you want to update the changelog as well, that's fine, or I can handle that (either way, I'll update the generated info manual).

**Comment by ryan-c-scott** [comment]
Created new [cleaner, saner] PR, #271 .

**Pull request closed without merging**
