### PR TITLE
Add: Dynamic Block (closed) column and sort

### PR DESCRIPTION
**Pull request by yejianye**
Add (closed) column and sort for dynamic block

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Thanks, these look like useful changes.  However:

1.  Adding a new sorting method and adding a new dynamic block column are distinct changes and should be done in separate commits.
2.  They should be documented in the changelog in the readme.
3. The `org-ql.info` file should not be modified directly, because it's generated from the readme in the `after-save-hook`.

If you'd be willing to split up this into separate commits and address those documentation issues, I'd be glad to merge it.

**Comment by yejianye** [comment]
Thanks for your suggestions. And I will address those issues accordingly. A few questions, 
1. As for adding changelog in README, which version should I put it into? 
2. Should I create a pull request to master or other development branch?

**Comment by yejianye** [comment]
Also, I saw you write changelog in a very organized way. Do you think it make sense for me to just update documentation for `org-ql-search` and `Dynamic Block`, and let you update the changelog?

**Comment by yejianye** [comment]
@alphapapa any feedbacks? Would be great if it could be merged back to master. Otherwise, I may need make the change again after I update org-ql to a new version. Since you're continuously adding new features, I think I will do upgrades pretty often.

**Comment by alphapapa** [comment]
Thanks for your patience.  I haven't had time to work on my packages much for a while.

1.  I'll take care of the changelog.
2. The PR should be for the master branch.  I use master for the development version, and branches for stable releases.

**Comment by alphapapa** [comment]
Thanks for your patience.

**Pull request merged**
